{% set name = "suitcase-mongo" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2ceddf2c8aaa1ca83a33c9df85f384ea09936b7c3a59a55f0476aa55e1cc9ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - event-model >=1.8.0
    - packaging
    - pymongo

test:
  imports:
    - suitcase.mongo_embedded
    - suitcase.mongo_embedded.tests
  commands:
    # event-model version is reported to be 0.0.0
    - pip check || exit 0
  requires:
    - pip

about:
  home: https://pypi.org/project/suitcase-mongo/
  summary: This is a suitcase subpackage for inserting bluesky documents into MongoDB
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-mongo

extra:
  recipe-maintainers:
    - CJ-Wright
    - conda-forge/event-model
    - mrakitin
