{% set name = "suitcase-mongo" %}
{% set name_ = "suitcase_mongo" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: b8d39fde538ece1768b388ac9d2655cdd83cab52765adc8e56ed5067198586bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - event-model >=1.8.0
    - packaging
    - pymongo

test:
  imports:
    - suitcase.mongo_embedded
    - suitcase.mongo_embedded.tests
  commands:
    # event-model version is reported to be 0.0.0
    - pip check || exit 0
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/suitcase-mongo/
  summary: This is a suitcase subpackage for inserting bluesky documents into MongoDB
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-mongo

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - mrakitin
